Discussion
greenelab/text_mined_hetnet_manuscript pull request #17
Opened 2019-07-23 03:14 UTC by danich1

This discussion section explains the reason for key findings of this project.

2019-07-24 09:20 UTC, cgreene requested changes
I reviewed partway and it became unclear which results justified many of the inferences that you are drawing from them. Perhaps addressing #20 will help with this. Can you go through and revise to include the claims that are supported by evidence in the paper, or add the evidence to the results section if it's important and not there yet.

2019-07-24 09:20 UTC, cgreene commented on content/05.discussion.md
> +An interesting finding is performance increases when text patterns and domain heuristic label functions are added on top of the distant supervision label functions.
```suggestion
```

2019-07-24 09:20 UTC, cgreene commented on content/05.discussion.md
> +This increase happens because curated databases have low coverage and end up missing information.
Do you have evidence for this? If so, I missed it. If not, it's probably best to delete it.

2019-07-24 09:20 UTC, cgreene commented on content/05.discussion.md
> +Some relationships are easier to predict than others.
```suggestion
We also observed that certain relationships were easier to predict than others.
```

2019-07-24 09:20 UTC, cgreene commented on content/05.discussion.md
> +For example, we achieved a significantly high area under the receiver operating curve (AUROC) and area under the precision recall curve (AUPR) for Compound-treats-Disease (CtD) (Figure {@fig:generati
```suggestion
For example, we achieved a significantly high AUROC and AUPR for CtD than other edge types (Figures {@fig:generative_model_auroc} and {@fig:generative_model_auprc}).
```

2019-07-24 09:20 UTC, cgreene commented on content/05.discussion.md
> +Reason for high performance is that wording is pretty straight forward when abstracts talk about this particular edge type.
Do you have evidence for this? If not, should delete.

2019-07-24 09:20 UTC, cgreene commented on content/05.discussion.md
> +Regarding Disease-associates-Gene (DaG), this edge type has a broad range of keywords that can infer associations.
There are a lot of assertions here and I didn't see evidence for them as I read the paper. For these claims where does the evidence come from? If it's not in the paper, it either needs to be in the paper or the claim should be removed.

2019-07-31 14:21 UTC, dhimmel reviewed
The discussion does a good job covering the questions and peculiarities uncovered by this work. Would be good to add a couple paragraphs on:

1. Summarizing the importance of this work
2. Discussing future directions... e.g. what does this study enable?

Update: just saw https://github.com/greenelab/text_mined_hetnet_manuscript/pull/18, disregard previous comment

2019-07-31 14:21 UTC, dhimmel commented on content/05.discussion.md
> +An interesting finding is performance increases when adding a single label funciton to the generative model baseline.
funciton is misspelled. Has "generative model baseline" been explained elsewhere? It's not entirely clear here that these label functions are in addition to the knowledge base labeling functions.

2019-07-31 14:21 UTC, dhimmel commented on content/05.discussion.md
> +Potential reasons for this is the discriminative model overfits to the generative model's predictions and there is a negative class bias for our datasets (Table {@tbl:candidate-sentences}).
> Potential reasons for this is

is should be are because the subject of "reasons" is plural

2019-07-31 14:21 UTC, dhimmel commented on content/05.discussion.md
> +Despite our efforts, model calibration didn't help performance (Figure {@fig:discriminative_model_calibration}).
When you say "didn't help performance", how are you judging performance? If using a method that only considers rank (like AUROC or AUPRC), then calibration CANNOT have an effect on performance.

2019-08-01 15:51 UTC, dhimmel approved these changes

2019-08-01 15:56 UTC, merged