Description of Dataset and the Generation Process
greenelab/text_mined_hetnet_manuscript pull request #5
Opened 2019-06-26 19:17 UTC by danich1

This is pr is for filling out the dataset description within the methods section. This is the first of *many* PRs as the target rate of submission is one section PR a day.

2019-06-26 19:50 UTC, cgreene requested changes
Initial thoughts. A couple points will need you to clarify and then we can run through them again.

2019-06-26 19:50 UTC, cgreene commented on content/03.methods.md
> +The dataset used for this project is called Pubtator [@doi:10.1093/nar/gkt441], which is an open source repository that contains pre-tagged medline abstracts.
```suggestion
We used PubTator [@doi:10.1093/nar/gkt441] as input to our analysis.
PubTator provides medline abstracts that have been annotated with well-established entity recognition tools including (X, Y, Z, ZZ, ZZZ...).
```

2019-06-26 19:50 UTC, cgreene commented on content/03.methods.md
> +It was downloaded on June 30, 2017 and contained 10,775,748 different abstracts.
```suggestion
We downloaded PubTator on June 30, 2017, at which point it contained 10,775,748 abstracts.
```

2019-06-26 19:50 UTC, cgreene commented on content/03.methods.md
> +After obtaining these abstracts, we filtered out mention tags that were not contained in hetionet.
```suggestion
We filtered out mention tags that were not contained in hetionet.
```

2019-06-26 19:50 UTC, cgreene commented on content/03.methods.md
> +After obtaining these abstracts, we filtered out mention tags that were not contained in hetionet.
As a note -what is hetionet? I think you need a section in your M&M on it.

2019-06-26 19:50 UTC, cgreene commented on content/03.methods.md
> +Following the tag filtering step, we used the Stanford CoreNLP parser [@doi:10.3115/v1/P14-5010] to do part of speech (POS) tagging and dependency tree generation.
```suggestion
We then used the Stanford CoreNLP parser [@doi:10.3115/v1/P14-5010] to tag parts of speech and generate dependency trees.
```

2019-06-26 19:50 UTC, cgreene commented on content/03.methods.md
> +Treating sentences with only a single mention as negative, we extracted sentences with two or more mentions, termed candidate sentences.
```suggestion
We extracted sentences with two or more mentions, termed candidate sentences, and considered sentences with only a single mention to be negatives.
```

2019-06-26 19:50 UTC, cgreene commented on content/03.methods.md
> +Treating sentences with only a single mention as negative, we extracted sentences with two or more mentions, termed candidate sentences.
I don't understand if this means you removed sentences that had only a single mention, or if they were included but used as negatives for ML somehow.

2019-06-26 19:50 UTC, cgreene commented on content/03.methods.md
> +After obtaining candidate sentences, we did a stratified sort of each candiadte into a training set, tuning set and a testing set (shown in Table 1).
```suggestion
We performed a stratified sort (STRATIFIED BY?) to produce a training set, tuning set and a testing set (shown in Table 1).
```

2019-06-26 19:50 UTC, cgreene commented on content/03.methods.md
> +Each sentence was sorted based on the present mention pair.
I see that this goes with above. Best to work it in there, but as written I also don't quite get it. You stratified sorted by entity or by pairs of entities?

2019-06-26 19:50 UTC, cgreene commented on content/03.methods.md
> +To obtain a ground truth set for each given relationship, we hand labeled five hundred to a thousand candidate sentences (shown in parenthesis in Table 1).
```suggestion
We hand labeled five hundred to a thousand candidate sentences of each relationship to obtain to obtain a ground truth set (Table 1).
```

2019-06-26 19:50 UTC, cgreene commented on content/03.methods.md
> +Table 1. Statistics of Candidate Sentences
```suggestion
Table 1. Statistics of Candidate Sentences. Numbers in parentheses show the number of positives and negatives that resulted from the hand-labeling process.
```

2019-06-28 08:56 UTC, cgreene requested changes
Just a few more suggestions. It would be good to get @dhimmel's review as well after you make the changes.

2019-06-28 08:56 UTC, cgreene commented on content/03.methods.md
> +All of the data in this network comes from publicly available databases, such as GWAS Catalog [@doi:10.1093/nar/gkw1133], DrugBank [@doi:10.1093/nar/gkw1133] and more.
```suggestion
Edges in Hetionet were obtained from open databases, such as the GWAS Catalog [@doi:10.1093/nar/gkw1133], DrugBank [@doi:10.1093/nar/gkw1133].
```

2019-06-28 08:56 UTC, cgreene commented on content/03.methods.md
> +For this project, we focus on the following relationship types: disease associates with a gene (DaG), compounds binding to a gene (CbG), gene interacts with gene (GiG) and compound treating a disease
```suggestion
For this project, we analyzed performance over a subset of the Hetionet relationship types: disease associates with a gene (DaG), compounds binding to a gene (CbG), gene interacts with gene (GiG) and compound treating a disease (CtD).
```

2019-06-28 08:56 UTC, cgreene commented on content/03.methods.md
> +![Hetionet_metagraph](images/figures/metagraph.png)
I think you should use a figure that shows only the relationship types that you actually used. _OR_ a figure like this one, where all of the types you didn't use are "faded" with, say, 70% transparency, into the background.

2019-06-28 16:13 UTC, cgreene commented on content/03.methods.md
> +Figure 1. A metagraph (schema) of Hetionet where pharmacological, biological and disease entities are represented as nodes and the relationships between them are represented as edges [@doi:10.7554/eL
```suggestion
Figure 1. A metagraph (schema) of Hetionet where pharmacological, biological and disease entities are represented as nodes and the relationships between them are represented as edges.
```

2019-06-28 16:13 UTC, cgreene commented on content/03.methods.md
> +Figure 1. A metagraph (schema) of Hetionet where pharmacological, biological and disease entities are represented as nodes and the relationships between them are represented as edges [@doi:10.7554/eL
Removed the ref now b/c the figure has been modified.

2019-06-28 16:14 UTC, cgreene approved these changes
One more minor change. Then @dhimmel review time. Merge at will after @dhimmel approves 👍

2019-07-03 17:33 UTC, dhimmel reviewed
Great use of one sentence per line! Off to a good start.

Sentences are nice and clear. Some comments.

2019-07-03 17:33 UTC, dhimmel commented on content/03.methods.md
> +This network depicts information in the form of nodes and edges of different types: nodes that represent biological and pharmacological entities and edges which represent relationships each entity ma
"relationships between entities" may be more clear than "relationships each entity may share with itself or another". The "share with itself" phrasing makes me think of self-loops. There are no self loops in Hetionet v1.0. Try the following Cypher query at https://neo4j.het.io/browser/:

```cypher
MATCH path=(source)-[rel]->(target)
WHERE source = target
RETURN type(rel), count(rel)
```

2019-07-03 17:33 UTC, dhimmel commented on content/03.methods.md
> +Currently, Hetionet contains 47,031 nodes with 11 different data types and 2,250,197 edges that represent 24 different relationship types (Figure 1).
You could also just say "Hetionet v1.0" rather than currently.

2019-07-03 17:33 UTC, dhimmel commented on content/03.methods.md
> +Edges in Hetionet were obtained from open databases, such as the GWAS Catalog [@doi:10.1093/nar/gkw1133], DrugBank [@doi:10.1093/nar/gkw1133].
missing "and" before DrugBank?

2019-07-03 17:33 UTC, dhimmel commented on content/03.methods.md
> +For this project, we analyzed performance over a subset of the Hetionet relationship types: disease associates with a gene (DaG), compounds binding to a gene (CbG), gene interacts with gene (GiG) and
"binding" is different tense than others. I'd use "binds" instead.

2019-07-03 17:33 UTC, dhimmel commented on content/03.methods.md
> +Figure 1. A metagraph (schema) of Hetionet where pharmacological, biological and disease entities are represented as nodes and the relationships between them are represented as edges.
Great figure. I like the transparency / fading to highlight which Hetionet relationships this study focuses on.

Should the caption discuss the fading (or whatever you want to call it).

See [proper syntax](https://github.com/manubot/rootstock/blob/master/USAGE.md#figures) for Figure caption (goes where alt text usually goes).

2019-07-03 17:33 UTC, dhimmel commented on content/03.methods.md
> +PubTator provides medline abstracts that have been annotated with well-established entity recognition tools including DNorm [@doi:10.1093/bioinformatics/btt474], GeneTUKit [@doi:10.1093/bioinformatic
Should you mention which entity types each tagger applies to?

medline should be capitalized like MEDLINE

2019-07-03 17:33 UTC, dhimmel commented on content/03.methods.md
> +We hand labeled five hundred to a thousand candidate sentences of each relationship to obtain to obtain a ground truth set (Table 1).
Probably want to use tablenos automated numbering
https://github.com/manubot/rootstock/blob/master/USAGE.md#tables

2019-07-03 17:33 UTC, dhimmel commented on content/03.methods.md
> +We hand labeled five hundred to a thousand candidate sentences of each relationship to obtain to obtain a ground truth set (Table 1).
Also link to the dataset with the hand labels here? Like "(table 1, dataset)"?

2019-07-03 17:33 UTC, dhimmel commented on content/03.methods.md
> +Table 1. Statistics of Candidate Sentences. Numbers in parentheses show the number of positives and negatives that resulted from the hand-labeling process.
Perhaps a brief comment on split into Train, Tune, Test in caption?

2019-07-03 17:33 UTC, dhimmel commented on content/03.methods.md
> +Each candidates sentence was stratified by co-mention pair to produce a training set, tuning set and a testing set (shown in Table 1).
The stratification procedure to preoduct traiin / tune / test is important. Not sure this description is sufficient (unless more details will be provided elsewhere)

2019-07-08 13:55 UTC, danich1 commented
This was verbally approved by @dhimmel. Merging and closing.

2019-07-08 13:55 UTC, merged